DVDManagement/Controllers/ClaimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using DVDManagement.Models;
using DVDManagement.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Claim = DVDManagement.Models.Claim;

namespace DVDManagement.Controllers
{
    public class ClaimController : Controller
    {
        private readonly AuthDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public ClaimController(AuthDbContext context,
                                UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            var claims = _context.Claims?.ToList();
            return View(claims);
        }

        public IActionResult New()
        {
            return View(new Models.Claim());
        }

        [HttpPost]
        public async Task<IActionResult> New(Models.Claim claim)
        {
            if (!ModelState.IsValid)
                return View(claim);

            claim.ClaimValue = claim.ClaimValue?.ToString();

            _context.Claims?.Add(claim);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> AssignClaimToUser(string userId)
        {
            var claims = _context.Claims?.ToList();
            claims = claims.Select(x =>
            {
                x.ClaimType = $"Type = {x.ClaimType} and Value = {x.ClaimValue}";
                return x;
            }).ToList();

            ViewBag.Claims = new SelectList(claims, "Id", "ClaimType");

            var user = await _userManager.FindByIdAsync(userId);
            ViewBag.UserName = user.UserName;
            ViewBag.UserId = userId;

            var userClaims = await _userManager.GetClaimsAsync(user);

            return View((List<System.Security.Claims.Claim>)userClaims);
        }

        [HttpPost]
        public async Task<IActionResult> AssignClaimToUser(string userId,int claimId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            var claim = _context.Claims?.FirstOrDefault(x => x.Id == claimId);

            await _userManager.AddClaimAsync(user, new System.Security.Claims.Claim(claim.ClaimType, claim.ClaimValue));

            return RedirectToAction(nameof(AssignClaimToUser),new { userId=userId});
        }

        [HttpGet]
        public async Task<IActionResult> RemoveClaimFromUser(string userId,string claimType,string claimValue)
        {
            var user = await _userManager.FindByIdAsync(userId);
            await _userManager.RemoveClaimAsync(user, new System.Security.Claims.Claim(claimType, claimValue));
            return RedirectToAction(nameof(AssignClaimToUser), new { userId=userId});
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var claim = _context.Claims?.FirstOrDefault(x => x.Id == id);
            if (claim != null) _context.Claims?.Remove(claim);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

DVDManagement/Controllers/DVDController.cs
using DVDManagement.Data;
using DVDManagement.Models;
using DVDManagement.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DVDManagement.Controllers
{
   
    public class DVDController : Controller
    {
        private readonly AuthDbContext dataBaseContext;

        public DVDController(AuthDbContext db)
        {
            dataBaseContext = db;
        }

        //function 1
        public IActionResult SearchActor(string searchString)
        {
            var actor = dataBaseContext!.ActorModel!.ToList();
            var castMember = dataBaseContext!.CastMemberModel!.ToList();
            var dvd = dataBaseContext!.DVDTitleModel!.ToList();

            var result = from c in castMember
                         join d in dvd on c?.DVDNumber equals d?.DVDNumber into table1
                         from t in table1.ToList()
                         join a in actor on c.ActorNumber equals a.ActorId into table2
                         from i in table2.ToList()
            select new ActorViewModel
                         {
                             castMember = c,
                             dvd = t,
                             actor = i,
                         };
            if (!String.IsNullOrEmpty(searchString))
            {
                var list = result.Where(x => x?.actor?.ActorSurname == (searchString)).ToList();
                return View(list);
            }
            else
            {
                return View(result);
            }
            
        }
        //function 11
        public IActionResult SearchCastMember(string searchString)
        {
            var actor = dataBaseContext!.ActorModel!.ToList();
            var castMember = dataBaseContext!.CastMemberModel!.ToList();
            var dvd = dataBaseContext!.DVDTitleModel!.ToList();
            var dvdCopy = dataBaseContext!.DVDCopyModel!.ToList();
            var loan = dataBaseContext!.LoanModel!.ToList();

            var result = from c in castMember
                join d in dvd on c?.DVDNumber equals d?.DVDNumber into table1
                from t in table1.ToList()
                join a in actor on c.ActorNumber equals a.ActorId into table2
                from i in table2.ToList()
                join d2 in dvdCopy on t.DVDNumber equals d2.DVDNumber into table3
                from dt in table3.ToList()
                join l in loan on dt.CopyNumber equals l.CopyNumber into table4
                from lt in table4.ToList()
                select new ActorLoanViewModel
                {
                    CastMember = c,
                    Dvd = t,
                    Actor = i,
                    DvdCopy = dt,
                    Loan = lt,
                    LoanCount = table4.Count(x => x?.DateReturned == DateTime.Parse("0001-01-01 00:00:00.0000000"))
                };
            
            if (!String.IsNullOrEmpty(searchString))
            {
                var list = result.Where(x => x?.Actor?.ActorSurname == (searchString)).ToList();
                return View(list);
            }
            else
            {
                return View(result);
            }
            
        }
        //function 5
        public IActionResult CopyNumberSearch(string searchString)
        {
            var member = dataBaseContext!.MemberModel!.ToList();
            var loan = dataBaseContext!.LoanModel!.ToList();
            var dvd = dataBaseContext!.DVDCopyModel!.ToList();

            var result = from l in loan
                                 join m in member on l.MemberNumber equals m?.MemberNumber into table1
                                 from t in table1.ToList()
                                 join d in dvd on l.CopyNumber equals d.CopyNumber into table2
                                 from i in table2.ToList()
                                 select new MemberCopyModel
                                 {
                                     loan = l,
                                     dvd = i,
                                     member = t,
                                 };
            
            if (!String.IsNullOrEmpty(searchString))
            {
                var list = result.Where(x => x?.loan?.CopyNumber == searchString).ToList();
                return View(list);
            }
            else
            {
                return View(result);
            }
        }

        public IActionResult ProducerList()
        {
            var producer = dataBaseContext!.ProducerModel!.ToList();
            var studio = dataBaseContext!.StudioModel!.ToList();
            var actor = dataBaseContext!.ActorModel!.ToList();
            var castMember = dataBaseContext!.CastMemberModel!.ToList();
            var dvd = dataBaseContext!.DVDTitleModel!.ToList();

            var result = from c in castMember
                         join d in dvd on c?.DVDNumber equals d?.DVDNumber into table1
                         from t in table1.ToList()
                         join a in actor on c.ActorNumber equals a.ActorId into table2
                         from i in table2.ToList()
                         join s in studio on t.StudioNumber equals s.StudioNumber into table3
                         from st in table3.ToList()
                         join p in producer on t.ProducerNumber equals p.ProducerNumber into table4
                         from pt in table4.ToList()
                         select new ProducerViewModel
                         {
                             producer = pt,
                             dvd = t,
                             castMember = c,
                             studio = st,
                             actor = i,
                         };
            //var list = result.Where(x => x?.loan?.CopyNumber == SearchString).ToList();
            return View(result);
        }
        
        
        //function 10
        public IActionResult OldDvdCopyList(bool copyDeleted = false)
        {
            ViewBag.copyDeleted = copyDeleted;
            DateTime currentDate = DateTime.Now.Date;
            DateTime lastDate = currentDate.Subtract(new TimeSpan(365, 0, 0, 0, 0));
            String d = "0";
            var loan = dataBaseContext.LoanModel?.ToList();
            var dvdCopy = dataBaseContext.DVDCopyModel?.ToList();

            var dvd = from dc in dvdCopy
                join l in loan on dc.CopyNumber equals l.CopyNumber into table1
                from l in table1.Distinct().Where(l => l.CopyNumber == dc.CopyNumber && l.DateReturned != DateTime.Parse("0001-01-01 00:00:00.0000000") && dc.DatePurchased < lastDate)

                select new { loan = l, dvdCopy = dc };
            ViewBag.dvdList = dvd;
            return View(dvd);
        }
        
        public async Task<IActionResult> DeleteCopy(string copynumber)
        {
            var copy = dataBaseContext.DVDCopyModel.Where(l => l.CopyNumber == copynumber).First();
            dataBaseContext.DVDCopyModel.Remove(copy);
            dataBaseContext.SaveChanges();
            return RedirectToAction("OldDvdCopyList", new { copyDeleted = true });
        }
        //function 11
        public IActionResult NotLoanedDvdCopyList()
        {
            String c = "0";
            var member = dataBaseContext.MemberModel?.ToList();
            var loan = dataBaseContext.LoanModel?.ToList();
            var dvdTitle = dataBaseContext.DVDTitleModel?.ToList();
            var dvdCopy = dataBaseContext.DVDCopyModel?.ToList();

            var copyloan = (from l in loan
                            join m in member on l.MemberNumber equals m.MemberNumber into table1
                            from m in table1.Distinct().ToList().Where(m => m.MemberNumber == l.MemberNumber).Distinct().ToList()
                            join dc in dvdCopy on l.CopyNumber equals dc.CopyNumber into table2
                            from dc in table2.Distinct().ToList().Where(dc => dc.CopyNumber == l.CopyNumber).Distinct().ToList()
                            join dt in dvdTitle on dc.DVDNumber equals dt.DVDNumber into table3
                            from dt in table3.Distinct().ToList().Where(dt => dt.DVDNumber == dc.DVDNumber && l.DateReturned != DateTime.Parse("0001-01-01 00:00:00.0000000")).Distinct().ToList()
                            group new { l, m, dc, dt } by new { dt.DVDTitle, dc.CopyNumber, m.MemberFirstName, l.DateOut }
                           into grp
                            select new
                            {
                                TotalLoans = grp.Count(),
                                grp.Key.DVDTitle,
                                grp.Key.CopyNumber,
                                grp.Key.MemberFirstName,
                                grp.Key.DateOut,

                            }).OrderBy(X => X.TotalLoans);
            ViewBag.totalloans = copyloan;
            return View(copyloan);
        }
        
        //function 8
        
        
        //function 7
        public IActionResult LoanedDvdList()
        {
            
            DateTime currentDate = DateTime.Now.Date;
            DateTime lastDate = currentDate.Subtract(new TimeSpan(365, 0, 0, 0, 0));
            String d = "0";
            var loan = dataBaseContext.LoanModel?.ToList();
            var member = dataBaseContext.MemberModel?.ToList();
            var loanDetail = (from l in loan
                join m in member on l.MemberNumber equals m.MemberNumber into table1
                from m in table1.ToList().Where(m => m.MemberNumber == l.MemberNumber && l.DateReturned == DateTime.Parse("0001-01-01 00:00:00.0000000"))
                orderby l.CopyNumber ascending
                select new { loan = l, member = m });
            ViewBag.loanDetails = loanDetail;
            return View(loanDetail);
        }
        public IActionResult EditDvdCopyDetails(string CopyNumber)
        {

DVDManagement/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/header.css" asp-append-version="true" />
    </head>
<body>

<div class="site-navbar-wrap">
      <div class="site-navbar-top">
        <div class="container py-3">
          <div class="row align-items-center">
            <div class="col-6">
              <div class="d-flex mr-auto">
                <a href="#" class="d-flex align-items-center mr-4">
                  <span class="icon-envelope mr-2"></span>
                  <span class="d-none d-md-inline-block">info@domain.com</span>
                </a>
                <a href="#" class="d-flex align-items-center mr-auto">
                  <span class="icon-phone mr-2"></span>
                  <span class="d-none d-md-inline-block">+1 234 4567 8910</span>
                </a>
              </div>
            </div>
            <div class="col-6 text-right">
              <div class="mr-auto">
                <a href="#" class="p-2 pl-0"
                  ><span class="icon-twitter"></span
                ></a>
                <a href="#" class="p-2 pl-0"
                  ><span class="icon-facebook"></span
                ></a>
                <a href="#" class="p-2 pl-0"
                  ><span class="icon-linkedin"></span
                ></a>
                <a href="#" class="p-2 pl-0"
                  ><span class="icon-instagram"></span
                ></a>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="site-navbar site-navbar-target js-sticky-header">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-2">
              <h1 class="my-0 site-logo"><a asp-controller="Home" asp-action="Index">Ropey DVD</a></h1>
            </div>
            <div class="col-10">
              <nav class="site-navigation text-right" role="navigation">
                <div class="container">
                  <div class="d-inline-block d-lg-none ml-md-0 mr-auto py-3">
                    <a
                      href="#"
                      class="site-menu-toggle js-menu-toggle text-white"
                      ><span class="icon-menu h3"></span
                    ></a>
                  </div>

                  <ul
                    class="site-menu main-menu js-clone-nav d-none d-lg-block"
                  >
                    <li class="active" style="background: #0a53be;
                                                  width: 103px;
                                                  height: 40px;
                                                  display: flex;
                                                  justify-content: center;
                                                  align-items: center;
                                                  padding: 20px;
                                                  border-radius: 5px;
                                                 float: right;
                                                  margin: 20px;">
                      <a href="Identity/Account/Login" class="nav-link" style="    margin-left: -3px;
                                                                                   font-size: 18px;
                                                                                   font-family: 'Poppins';">Login</a>
                    </li>
                  </ul>
                </div>
              </nav>
            </div>
          </div>
        </div>
      </div>
    </div>

@RenderBody()

</body>
</html>

DVDManagement/Views/Shared/_IndexLayout.cshtml
<!DOCTYPE html>
<html>
<head>
     <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - DVDManagement</title>
     <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
     <link rel="stylesheet" href="~/css/auth.css" asp-append-version="true" />
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css" integrity="sha512-rRQtF4V2wtAvXsou4iUAs2kXHi3Lj9NE7xJR77DE7GHsxgY9RTWy93dzMXgDIG8ToiRTD45VsDNdTiUagOFeZA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
     <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
     </head>
<body>

@RenderBody()

</body>
<script>
(function($) {

    $(".toggle-password").click(function() {

        $(this).toggleClass("zmdi-eye zmdi-eye-off");
        var input = $($(this).attr("toggle"));
        if (input.attr("type") === "password") {
          input.attr("type", "text");
        } else {
          input.attr("type", "password");
        }
      });

})(jQuery);
</script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</html>

DVDManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RopeyDVD </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true" />
</head>
<body>
@*<header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DVDManagement</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>*@
<header class="site-navbar site-navbar-target bg-white" role="banner" style="z-index: 0; position: sticky">
    <div class="container">
          <div class="row align-items-center position-relative">
              <div class="col-lg-4">
              <nav class="site-navigation text-right ml-auto " role="navigation">
                <ul class="site-menu main-menu js-clone-nav ml-auto d-none d-lg-block">
                  <li class="active"><a asp-area="" asp-controller="HomePage" asp-action="Index" class="nav-link">Home</a></li>
                    <li>
                        <div class="dropdown">
                            <a class="dropdown-toggle" href="#" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                                DVD
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                <li><a class="dropdown-item" asp-controller="DVD" asp-action="CopyNumberSearch">Copy Number Search</a></li>
                                <li><a class="dropdown-item" asp-controller="DVD" asp-action="LoanedDvdList">Loaned DVD List</a></li>
                                <li><a class="dropdown-item" asp-controller="DVD" asp-action="NotLoanedDvdCopyList">Not Loaned DVD Copy</a></li>
                                <li><a class="dropdown-item" asp-controller="DVD" asp-action="OldDvdCopyList">Old DVD Copy List</a></li>
                                <li><a class="dropdown-item" asp-controller="DVD" asp-action="ProducerList">Producer List</a></li>
                                <li><a class="dropdown-item" asp-controller="DVD" asp-action="SearchActor">Search Actor</a></li>
                                <li><a class="dropdown-item" asp-controller="DVD" asp-action="SearchCastMember">Search Actor Member</a></li>
                            </ul>
                        </div>
                    </li>
                  <li><a asp-area="" asp-controller="UserRoleManagement" asp-action="Index" class="nav-link">User Role</a></li>
                </ul>
              </nav>
            </div>
            <div class="col-lg-4 text-center">
              <div class="site-logo">
                <a class="navbar-brand " asp-area="" asp-controller="HomePage" asp-action="Index">Ropey DVD</a>
              </div>
                <div class="ml-auto toggle-button d-inline-block d-lg-none"><a href="#" class="site-menu-toggle py-5 js-menu-toggle text-black"><span class="icon-menu h3 text-black"></span></a></div>
            </div>
            <div class="col-lg-4">
              <nav class="site-navigation text-left mr-auto " role="navigation">
                  <ul class="site-menu main-menu js-clone-nav ml-auto d-none d-lg-block">
                      <li><div class="dropdown">
                            <a class="dropdown-toggle" href="#" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                              Assistance
                            </a>
                          <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                              <li><a class="dropdown-item" asp-controller="Assistance" asp-action="AddDVDCopy">Add DVD Copy Copy</a></li>
                              <li><a class="dropdown-item" asp-controller="Assistance" asp-action="CreateDVDTitle">Create DVD Title</a></li>
                                <li><a class="dropdown-item" asp-controller="Assistance" asp-action="GetDVDofNoLoan">Get DVD Of No Loan</a></li>
                                <li><a class="dropdown-item" asp-controller="Assistance" asp-action="ProducerDvdList">Producer DVD List</a></li>
                                <li><a class="dropdown-item" asp-controller="Assistance" asp-action="ResetPassword">Reset Password</a></li>
                            </ul>
                          </div></li>
                      <li><div class="dropdown">
                                                  <a class="dropdown-toggle" href="#" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                                                    Member
                                                  </a>
                                                  
                                                  <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                                    <li><a class="dropdown-item" asp-controller="MemberController" asp-action="MemberListNotBorrowed">Member not Loaned in 30 days</a></li>
                                                      <li><a class="dropdown-item" asp-controller="Assistance" asp-action="CreateDVDTitle">MmmberTotalLoans</a></li>
                                                      <li><a class="dropdown-item" asp-controller="Assistance" asp-action="CreateDVDTitle">No Loaned Members</a></li>
                                                  </ul>
                                                </div></li>
                      <button class="login-btn"><a asp-controller="Home" asp-action="Logout">Logout</a> </button>
                  </ul>
              </nav>
            </div>
          </div>
        </div>
</header>
    <div class="container" style="height: 100vh">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DVDManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DVDManagement/Views/Shared/_TopMenuPartial.cshtml
<div class="row" style="margin-bottom:10px;">
    <div class="col-8 offset-2">
        <a asp-action="AddRole" asp-controller="UserRoleManagement" class="btn btn-primary mr-2">New Role</a>
        <a asp-action="New" asp-controller="Claim" class="btn btn-info mr-2">New Claim</a>
        <a asp-action="Index" asp-controller="Claim" class="btn btn-success mr-2">View Claim</a>
        <a asp-action="DisplayRoles" asp-controller="UserRoleManagement" class="btn btn-success mr-2">View Roles</a>
        <a asp-action="AddUserToRole" asp-controller="UserRoleManagement" class="btn btn-info mr-2">Assign user to role</a>
        <a asp-action="Index" asp-controller="UserRoleManagement" class="btn btn-primary">Go Back</a>
    </div>
</div>

<hr/>